### PR TITLE
Add default listen port for local server

### PR DESCRIPTION
**Pull request by ductilestudios**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)

Closes #XXXXX

I noticed the second boilerplate includes port 3000 as a default for Node to listen on when running locally.  This would've been super helpful on the initial setup, but it was a great exercise in debugging I suppose :).  Having things a little smoother out of the gates would ease frustration I'm sure.

### CODE REVIEW

**Comment by scissorsneedfoodtoo** [comment]
Hi @ductilestudios, thanks for catching this issue and for your fix.

I took a quick look and everything looks good. However, we recently fixed some other boilerplates with a similar issue and used a slightly different method: https://github.com/freeCodeCamp/boilerplate-project-messageboard/pull/17/files#diff-a4c65ede64197e1a112899a68bf994485b889c4b143198bac4af53425b38406fR50-R51

Would you mind updating this PR to use the same method? I believe it should be something like this:

```js
const listener = app.listen(process.env.PORT || 3000, function () {
  console.log('Your app is listening on port ' + listener.address().port);
});
```

**Comment by ductilestudios** [comment]
Sounds god @scissorsneedfoodtoo revised and tested as requested

**Review by gikf — APPROVED** [review]
LGTM :+1:

**Review by ShaunSHamilton — APPROVED** [review]
This LGTM 👍

**Comment by ShaunSHamilton** [comment]
Congrats on your first PR to this repository! 🎉

Thank you, for your contribution to the page! 👍
We are happy to accept these changes, and look forward to future contributions. 📝

**Pull request merged**
