### PR TITLE
author lesson

### PR DESCRIPTION
**Pull request by ManMyth0**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

### CODE REVIEW

**Comment by ManMyth0** [comment]
Tryin to figure this out

**Comment by gikf** [comment]
Hey @ManMyth0

Looks like this PR was supposed to be made on your own fork, instead of the original boilerplate repository.

This is a standard message notifying you that we've reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

Thank you and happy coding.

**Comment by ManMyth0** [comment]
Ok thank you. Still learning. Would be helpful if I could be pointed in the right direction for using vs code with GitHub for submissions but replit seems to be working out for me. Any suggestions? I’d be happy to hear them. Thanks for your time

.

**Comment by gikf** [comment]
Usually it's required to provide link to the project _working live_, so submitting it from github won't do it.

**Pull request closed without merging**
